services:
  app:
    build:
      context: .
      args:
        - DEV=True
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=skinapp
      - DB_USER=skinapp_user
      - DB_PASSWORD=your_password_here
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=skinapp
      - POSTGRES_USER=skinapp_user
      - POSTGRES_PASSWORD=your_password_here

volumes:
  dev-db-data:
