# Generated by Django 5.2.13 on 2026-04-30 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcernTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concern_key', models.CharField(help_text='Concern key — e.g. acne, pigmentation, dullness', max_length=100, unique=True)),
                ('weeks', models.CharField(help_text='Expected improvement window — e.g. 4-6 or 8-12', max_length=20)),
                ('popup_text', models.TextField(help_text='Message shown in the timeline popup card on the result page')),
                ('purge_warning', models.BooleanField(default=False, help_text='True if skin may temporarily worsen before improving')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Concern Timeline',
                'verbose_name_plural': 'Concern Timelines',
                'ordering': ['concern_key'],
            },
        ),
        migrations.CreateModel(
            name='FaceMask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Mask name — e.g. Multani Mitti Cooling Mask', max_length=200)),
                ('benefit', models.TextField(help_text='One sentence about what this mask does')),
                ('frequency', models.CharField(help_text='How often to use — e.g. Once per week', max_length=100)),
                ('warning', models.TextField(blank=True, help_text='Safety warning shown at bottom of card — leave blank if none')),
                ('for_types', models.TextField(help_text='Comma-separated skin types — e.g. Oily,Combination')),
                ('for_concerns', models.TextField(help_text='Comma-separated concern keys — e.g. acne,oiliness,comedones')),
                ('avoid_if', models.TextField(blank=True, help_text='Comma-separated disqualifiers — e.g. Dry,Sensitized,Compromised Barrier')),
                ('safe_level', models.CharField(choices=[('all', 'All skin including sensitive'), ('normal_only', 'Normal skin only — not for sensitized or compromised barrier')], default='normal_only', help_text='Who can receive this mask recommendation', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Face Mask',
                'verbose_name_plural': 'Face Masks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Internal code key — e.g. niacinamide, salicylic_acid. Must match logic.py.', max_length=100, unique=True)),
                ('label', models.CharField(help_text='Display name shown in the routine — e.g. Niacinamide 5%', max_length=200)),
                ('why', models.TextField(help_text='Why this ingredient is used — shown to the user on the result page')),
                ('targets', models.TextField(help_text='Comma-separated concern keys — e.g. acne,oiliness,dullness')),
                ('sensitivity_safe', models.BooleanField(default=False, help_text='True = safe for reaction=burning or redness users')),
                ('dehydrated_safe', models.BooleanField(default=False, help_text='True = safe for Dehydrated skin state users')),
                ('phase_min', models.IntegerField(default=2, help_text='Earliest phase: 1=foundation, 2=treatment, 3=enhancement')),
                ('product_type', models.CharField(help_text='e.g. serum, moisturizer, toner/cleanser, eye cream', max_length=100)),
                ('time', models.CharField(help_text='AM, PM, or AM/PM', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to disable without deleting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='NextGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concern_key', models.CharField(help_text='Concern key this next goal applies to', max_length=100, unique=True)),
                ('goal_text', models.TextField(help_text='Text shown at the bottom of the result page after the timeline')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Next Goal',
                'verbose_name_plural': 'Next Goals',
                'ordering': ['concern_key'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_key', models.CharField(help_text='Ingredient key this product is recommended for — must match Ingredient.key', max_length=100)),
                ('name', models.CharField(help_text='Full product name as shown on the result page', max_length=300)),
                ('note', models.CharField(help_text='Short reason this product was chosen — e.g. Affordable and widely available in BD', max_length=300)),
                ('buy_link', models.URLField(blank=True, help_text='Purchase or affiliate link — leave blank if not available')),
                ('compatible_skin_types', models.TextField(blank=True, help_text='Comma-separated skin types — leave blank for all types')),
                ('sensitivity_safe', models.BooleanField(default=False, help_text='True = safe to recommend to reactive skin users')),
                ('budget_tier', models.CharField(choices=[('low', 'Low — under 500 BDT'), ('medium', 'Medium — 500 to 1500 BDT'), ('high', 'High — over 1500 BDT')], default='medium', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['ingredient_key', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkinGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Internal key — e.g. glow, glass_skin, pore_minimizing', max_length=100, unique=True)),
                ('label', models.CharField(help_text='Checkbox label shown on the form — e.g. Natural Glow', max_length=200)),
                ('roadmap_text', models.TextField(help_text='Explanation shown in Phase 3 goal card on the result page')),
                ('requires_stable', models.TextField(blank=True, help_text='Comma-separated concern keys that block this goal — leave blank if no prerequisites')),
                ('naturally_supported_by', models.TextField(blank=True, help_text='Comma-separated concern keys whose treatment also supports this goal')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skin Goal',
                'verbose_name_plural': 'Skin Goals',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='AvoidIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concern_key', models.CharField(help_text='Concern that triggers this avoidance — e.g. acne', max_length=100)),
                ('ingredient_name', models.CharField(help_text='Ingredient to avoid — shown as red tag on result page', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Avoid Ingredient',
                'verbose_name_plural': 'Avoid Ingredients',
                'ordering': ['concern_key', 'ingredient_name'],
                'unique_together': {('concern_key', 'ingredient_name')},
            },
        ),
        migrations.CreateModel(
            name='ConflictPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concern_a', models.CharField(help_text='First concern in the conflict pair', max_length=100)),
                ('concern_b', models.CharField(help_text='Second concern in the conflict pair', max_length=100)),
                ('reason', models.TextField(blank=True, help_text='Why these concerns conflict — for admin documentation only')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to disable this conflict pair without deleting')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conflict Pair',
                'verbose_name_plural': 'Conflict Pairs',
                'ordering': ['concern_a', 'concern_b'],
                'unique_together': {('concern_a', 'concern_b')},
            },
        ),
        migrations.CreateModel(
            name='FaceMaskIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Full ingredient line — e.g. 2 tablespoons Multani Mitti', max_length=300)),
                ('order', models.IntegerField(default=0, help_text='Display order — lower number shows first')),
                ('mask', models.ForeignKey(help_text='The mask this ingredient belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='skin.facemask')),
            ],
            options={
                'verbose_name': 'Mask Ingredient',
                'verbose_name_plural': 'Mask Ingredients',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FaceMaskStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Full instruction for this step', max_length=500)),
                ('order', models.IntegerField(default=0, help_text='Display order — lower number shows first')),
                ('mask', models.ForeignKey(help_text='The mask this step belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='skin.facemask')),
            ],
            options={
                'verbose_name': 'Mask Step',
                'verbose_name_plural': 'Mask Steps',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlainTextKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concern_key', models.CharField(help_text='Concern this keyword maps to — e.g. acne', max_length=100)),
                ('keyword', models.CharField(help_text='Keyword to scan for in user description — store lowercase — e.g. pimple', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plain Text Keyword',
                'verbose_name_plural': 'Plain Text Keywords',
                'ordering': ['concern_key', 'keyword'],
                'unique_together': {('concern_key', 'keyword')},
            },
        ),
        migrations.CreateModel(
            name='SkinGoalIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Phase 3 ingredient shown in the goal card — e.g. Vitamin C 10%', max_length=300)),
                ('order', models.IntegerField(default=0, help_text='Display order — lower number shows first')),
                ('goal', models.ForeignKey(help_text='The goal this Phase 3 ingredient belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='phase3_ingredients', to='skin.skingoal')),
            ],
            options={
                'verbose_name': 'Goal Ingredient',
                'verbose_name_plural': 'Goal Ingredients',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserSkinProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Django session key for anonymous tracking', max_length=100)),
                ('skin_type', models.CharField(max_length=50)),
                ('skin_states', models.TextField(blank=True, help_text='Comma-separated detected state names')),
                ('top_concerns', models.TextField(blank=True, help_text='Comma-separated top concern keys')),
                ('conflict_detected', models.BooleanField(default=False)),
                ('primary_concern', models.CharField(blank=True, max_length=100)),
                ('routine_start_date', models.DateTimeField(blank=True, help_text='When user started their routine — set when Start button is tapped', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_user', models.ForeignKey(blank=True, help_text='Linked user account — null until user accounts are implemented', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skin_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Skin Profile',
                'verbose_name_plural': 'User Skin Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
