# Generated by Django 5.2.14 on 2026-05-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskinprofile',
            name='raw_input',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
