# Generated by Django 5.2.12 on 2026-03-12 18:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('weight_kg', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('chest_cm', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('waist_cm', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('hips_cm', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('shoulder_cm', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('body_shape', models.CharField(blank=True, choices=[('triangle', 'Triangle'), ('inverted_triangle', 'Inverted Triangle'), ('rectangle', 'Rectangle'), ('hourglass', 'Hourglass'), ('oval', 'Oval')], max_length=20)),
                ('face_shape', models.CharField(blank=True, choices=[('oval', 'Oval'), ('round', 'Round'), ('square', 'Square'), ('heart', 'Heart'), ('diamond', 'Diamond')], max_length=20)),
                ('skin_type', models.CharField(blank=True, choices=[('normal', 'Normal'), ('oily', 'Oily'), ('dry', 'Dry'), ('combination', 'Combination'), ('sensitive', 'Sensitive')], max_length=20)),
                ('vein_color', models.CharField(blank=True, choices=[('green', 'Green'), ('blue', 'Blue / Purple'), ('mixed', 'Mixed')], max_length=10)),
                ('undertone', models.CharField(blank=True, choices=[('warm', 'Warm'), ('cool', 'Cool'), ('neutral', 'Neutral')], editable=False, help_text='Auto-derived from vein_color (green=warm, blue/purple=cool, mixed=neutral).', max_length=10)),
                ('favourite_season', models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter')], max_length=10)),
                ('recommended_palette', models.JSONField(blank=True, null=True)),
                ('shirt_size', models.CharField(blank=True, max_length=10)),
                ('pants_size', models.CharField(blank=True, max_length=10)),
                ('shoe_size', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('body_photo', models.ImageField(blank=True, null=True, upload_to='body_photos/')),
                ('face_photo', models.ImageField(blank=True, null=True, upload_to='face_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='body_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
